# Generated by Django 5.1.6 on 2025-02-12 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenciadosDeOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenciadosdeoffice', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoDeEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantenimientodeequipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaDelEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcadelequipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciasDeLicencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenciasdelicencias', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodedisco', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UltimosDigitosDeLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimosdigitosdelicencia', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VersionOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionWindows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windows', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('per_documento', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('per_nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellidos', models.CharField(max_length=150)),
                ('referencia_equipo', models.CharField(max_length=150)),
                ('tipo_De_torre', models.CharField(max_length=150)),
                ('ram', models.PositiveIntegerField()),
                ('referencia_licencia', models.CharField(max_length=150)),
                ('ultimos_digitos_licencia', models.CharField(max_length=3)),
                ('se_le_instalo_licencia', models.CharField(max_length=150)),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajadores.disco')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajadores.estado')),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajadores.procesador')),
                ('version_de_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajadores.versionoffice')),
                ('version_de_windows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trabajadores.versionwindows')),
            ],
        ),
    ]
