# Generated by Django 5.1.6 on 2025-02-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modalidad',
            new_name='Personas',
        ),
    ]
